# These substitutions allow the end user to override certain values
substitutions:
  name: "ziv-5ctm"
  friendly_name: "ZIV 5CTM Smart Meter"

packages:
  d1mini: !include d1mini.yaml
  piggymeter: !include piggymeter-d1mini.yaml
  ziv-5ctm: !include ziv-5ctm.yaml

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: "ZIV 5CTM Smart Meter"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

# Enable logging
logger:
  level: WARN
  # level: VERBOSE
  # initial_level: DEBUG

# Enable Home Assistant API
api:

# OTA is required for Over-the-Air updating
ota:
  - platform: esphome
    id: ota_esphome

wifi:
  min_auth_mode: WPA2
  # Set up a wifi access point using the device name above
  ap:

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:
